### ISSUE TITLE
Confusing semantic of IMPORT_FROM_EXA parameter

### ISSUE THREAD

**Issue by exaSR** [exasol/exasol-virtual-schema#89]
* Observation: 
  * `IMPORT_FROM_EXA = 'false'` does not work
  * `ALTER VIRTUAL SCHEMA CDP3_CDP SET IMPORT_FROM_EXA = Null;` works
* Expected: `IMPORT_FROM_EXA = 'false'` works, too

### Original Report 
Adapter Version: `virtual-schema-dist-10.1.0-exasol-7.0.2`

Given the example usage of
> IMPORT_FROM_EXA = 'true'

One would assume that an explicit negation should work; alas, it does not:

```sql
CREATE VIRTUAL SCHEMA CDP3_CDP
USING VSA.EXASOL_ADAPTER WITH
    CONNECTION_NAME = 'CDP_JDBC'
    SCHEMA_NAME     = 'CDP'
    IMPORT_FROM_EXA = 'false'
;
-- takes a few seconds to read metadata

select count(*) from cdp3_cdp.account_sf;
-- results in error:
```

```text
[Code: 0, SQL State: 22002]  VM error: F-UDF-CL-LIB-1126: F-UDF-CL-SL-JAVA-1006: F-UDF-CL-SL-JAVA-1026: 
com.exasol.ExaUDFException: F-UDF-CL-SL-JAVA-1068: Exception during singleCall adapterCall 
java.lang.IllegalArgumentException: E-VSEXA-1: Incomplete remote connection information Please specify a named EXA connection 'EXA_CONNECTION' for the ExaLoader and a named JDBC connection with 'CONNECTION_NAME' for the Virtual Schema adapter.
com.exasol.adapter.dialects.exasol.ExasolConnectionDefinitionBuilder.buildImportFromExaConnectionDefinition(ExasolConnectionDefinitionBuilder.java:40)
com.exasol.adapter.dialects.exasol.ExasolConnectionDefinitionBuilder.buildConnectionDefinition(ExasolConnectionDefinitionBuilder.java:23)
com.exasol.adapter.dialects.rewriting.AbstractQueryRewriter.rewrite(AbstractQueryRewriter.java:49)
com.exasol.adapter.dialects.AbstractSqlDialect.rewriteQuery(AbstractSqlDialect.java:141)
com.exasol.adapter.jdbc.JDBCAdapter.pushdown(JDBCAdapter.java:243)
com.exasol.adapter.AdapterCallExecutor.executePushDownRequest(AdapterCallExecutor.java:117)
com.exasol.adapter.request.PushDownRequest.executeWith(PushDownRequest.java:66)
com.exasol.adapter.AdapterCallExecutor.executeAdapterCall(AdapterCallExecutor.java:34)
com.exasol.adapter.RequestDispatcher.processAdapterCall(RequestDispatcher.java:55)
com.exasol.adapter.RequestDispatcher.adapterCall(RequestDispatcher.java:33)
com.exasol.ExaWrapper.runSingleCall(ExaWrapper.java:101)
 (Session: 1758344366162313216)
```

**Comment by exaSR** [comment]
Update:
```sql
ALTER VIRTUAL SCHEMA CDP3_CDP SET IMPORT_FROM_EXA = Null;
```
seems to work.

**Comment by ckunki** [comment]
Root cause seems to be that 
* some places handle `IMPORT_FROM_EXA` as an adapter property expecting a string representing boolean value (i.e. "true" or "false", case-insensitive) 
* other places just check if the adapter property is present (regardless of the value)

I propose to change implementation to the following behavior 
* explicitly define `IMPORT_FROM_EXA` as an optional boolean adapter property 
* if property has a value other than "true" or "false", case-insensitive then VSEXA throws an exception 
* if property is specified with value "true" then import-semantics is used 
* in all other cases import-semantics is *not* used

**Comment by ckunki** [comment]
Thanks for immediate feedback - sorry, for the issue lying some weeks.
